### ISSUE TITLE
document citeproc.js changes?

### ISSUE THREAD

**Issue by titaniumbones** [zotero/citeproc-js-server#23]
The readme says citeproc.js needs to be modified to work with node.  Can you describe these changes and/or submit them to upstream as patches? i would like to experiment with some additional output formats, in a way that maximises chances of acceptance both here and upstream.

**Comment by ailintom** [comment]
If one compares the citeproc.js file in citeproc-node with the original file of version 1.1.63, one sees that citeproc-node uses csl_json.js (copied from xmljson.js from the citeproc-js project), and does not use csl_nodejs_jsdom.
Whence the only two differences in citeproc.js.
line 574 (of the original file) ` var CSL_NODEJS = require("./csl_nodejs_jsdom").CSL_NODEJS_JSDOM;`  
becomes `var CSL_JSON = require("./csl_json.js").CSL_JSON;` in citeproc-node.
lines 593-595 of the original file
`if ("undefined" !== typeof CSL_IS_NODEJS) {`     
    `XML_PARSING = CSL_NODEJS;`    
`} else if ("undefined" !== typeof CSL_E4X) {`   
are replaced with `if ("undefined" !== typeof CSL_E4X) {`  
 in citeproc-node.

**Comment by dstillman** [comment]
I don't think modifications are required anymore.
