### ISSUE TITLE
Upgrade?

### ISSUE THREAD

**Issue by ivos** [zotero/citeproc-js-server#40]
Hello and thanks a lot for this project, it's really handy.

I'd like to ask whether there could be some hope in upgrading all the dependencies. They are 2 years old now and  have moved forward in the meantime. Specifically, it's about upgrading:

- The CSL repo, https://github.com/citation-style-language/styles - there are many new / updated styles there that are missing here
- The CSL Locales repo: https://github.com/citation-style-language/locales
- The Citeproc JS itself, from v. 1.1.210 to the current 1.4.4: https://github.com/Juris-M/citeproc-js

Thank you

**Comment by ivos** [comment]
I've created a PR here: https://github.com/zotero/citeproc-js-server/pull/41

**Comment by dstillman** [comment]
I've updated dependencies.
